# Generated by Django 5.1.3 on 2024-12-17 17:07

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='user_id',
            field=models.CharField(default=chat.models.generate_short_user_id, editable=False, max_length=4, unique=True),
        ),
    ]
