# Generated by Django 5.1.3 on 2024-12-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_anonymoususer_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususer',
            name='is_online',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
