# Generated by Django 5.1.3 on 2024-12-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_anonymoususer_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususer',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='anonymoususer',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
